# Generated by Django 4.2.11 on 2024-03-17 14:32

from django.db import migrations

def create_data(apps, schema_editor):
    Message = apps.get_model('youtube_assistant', 'Message')
    Message(origin='system', text='Hello! I am your personal youtube assistant. How can I help you?').save()
    Message(origin='user', text='Hello! Whats this video about?').save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('youtube_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
